apiVersion: apps/v1
kind: Deployment
metadata:
  name: delay-metric-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: delay-metric
  template:
    metadata:
      annotations:
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        app: delay-metric
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: delay-metric-config
          image: storefeegmail/httpserver:v1.0.3
          imagePullPolicy: IfNotPresent
          name: delay-metric
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 2
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1000m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 200Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 20